### ISSUE TITLE
Installing FPMods

### ISSUE THREAD

**Issue by paultpearson** [rrbruner/FPMods#20]
Hi all,

I'm looking for help installing FPMods and any advice is appreciated.  To install FPMods do I need to install sage from source?  Is there a way to install FPMods if sage was not built from source?  Is there a way to include/import the .py files directly in an ipynb to just import the python code directly rather than installing the module?  (You don't have to answer all my questions -- I'm just looking for one installation solution.)

I'm on Ubuntu 18.04. I previously had sage 8.1 installed using `sudo apt-get install sagemath` and switched to sage 9.2 installed via a conda this morning after failing to install sage 9.2 from source last night.  I can try a source install again if necessary.

Thanks!
Paul Pearson

**Comment by sverre320** [comment]
I made all our import statement paths relative, so this package can be run with a prebuilt version of Sage.  (Tested with my Sage 8.1 on my Ubuntu 18.04.2 LTS release.)

Instructions:

1. From this github repository, get the latest version of fpmods from the branch called "trac-review".

2. Go to your working directory, create a directory called "fpmods" and put all the *.py files in there.

3. From your working directory, run sage and test the package like this:

sage: from fpmods.fpa_module import *
sage: A = SteenrodAlgebra(2)
sage: M = FPA_Module([0], A, [[Sq(2)]])
sage: M
Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis
sage: hom = Hom(M.suspension(7), M)
sage: hom
Set of Morphisms from Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis to Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis in Category of modules over mod 2 Steenrod algebra, milnor basis
sage: hom.basis_elements(0)
[Module homomorphism of degree 0 defined by sending the generators
   [<1>]
 to
   [<Sq(0,0,1)>],
 Module homomorphism of degree 0 defined by sending the generators
   [<1>]
 to
   [<Sq(1,2) + Sq(4,1)>]]
sage:

**Comment by paultpearson** [comment]
Success!!!!  Thank you!  Thank you!  Thank you!  This is awesome!!!!

I hope that making relative paths was not hard and is not one more thing to maintain (or let go fallow).

My goal is to be able to make some module definition files (for Bob Bruner's ext program) for some cyclic modules over the Steenrod algebra.

Here's a brief log of what I did (i.e., a record for my future self and anyone else who wants to replicate this).

- https://doc.sagemath.org/html/en/installation/conda.html

(base) paul@paul:~$ conda config --add channels conda-forge
(base) paul@paul:~$ conda create -n sage sage python=3.9

- output from creating sage using conda is omitted, but build process was easy and successful

- downloaded FPMods trac-review branch as github as a zip from https://github.com/rrbruner/FPMods/tree/trac-review

(sage) paul@paul:~/ext/fpmods$ unzip FPMods-trac-review.zip 
Archive:  FPMods-trac-review.zip
3d3fdd5b69fb2686c9cc800b84edc5dab592dcc1
   creating: FPMods-trac-review/
  inflating: FPMods-trac-review/Mike_FP_Mods.pdf  
 extracting: FPMods-trac-review/__init__.py  
  inflating: FPMods-trac-review/all.py  
  inflating: FPMods-trac-review/build.sh  
  inflating: FPMods-trac-review/fp_element.py  
  inflating: FPMods-trac-review/fp_homspace.py  
  inflating: FPMods-trac-review/fp_module.py  
  inflating: FPMods-trac-review/fp_morphism.py  
  inflating: FPMods-trac-review/fpa_element.py  
  inflating: FPMods-trac-review/fpa_homspace.py  
  inflating: FPMods-trac-review/fpa_module.py  
  inflating: FPMods-trac-review/fpa_morphism.py  
  inflating: FPMods-trac-review/free_element.py  
  inflating: FPMods-trac-review/free_homspace.py  
  inflating: FPMods-trac-review/free_module.py  
  inflating: FPMods-trac-review/free_morphism.py  
  inflating: FPMods-trac-review/profile.py  
  inflating: FPMods-trac-review/run.sh  
(sage) paul@paul:~/ext/fpmods$ mkdir fpmods
(sage) paul@paul:~/ext/fpmods$ cp FPMods-trac-review/*.py ./fpmods/
(sage) paul@paul:~/ext/fpmods$ cd fpmods/
/home/paul/ext/fpmods/fpmods
(sage) paul@paul:~/ext/fpmods/fpmods$ ls
all.py		 fpa_morphism.py  fp_morphism.py    free_morphism.py
fpa_element.py	 fp_element.py	  free_element.py   __init__.py
fpa_homspace.py  fp_homspace.py   free_homspace.py  profile.py
fpa_module.py	 fp_module.py	  free_module.py
(sage) paul@paul:~/ext/fpmods/fpmods$ cd ..
(sage) paul@paul:~/ext/fpmods$ ls
fpmods	FPMods-trac-review  FPMods-trac-review.zip  old
(sage) paul@paul:~/ext/fpmods$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.2, Release Date: 2020-10-24                     │
│ Using Python 3.9.0. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: from fpmods.fpa_module import *
sage: M = FPA_Module([0],A,[[Sq(2)]])
sage: M
Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis
sage: hom = Hom(M.suspension(7),M)
sage: hom
Set of Morphisms from Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis to Finitely presented module on 1 generator and 1 relation over mod 2 Steenrod algebra, milnor basis in Category of modules over mod 2 Steenrod algebra, milnor basis
sage: hom.basis_elements(0)
[Module homomorphism of degree 0 defined by sending the generators
   [<1>]
 to
   [<Sq(0,0,1)>],
 Module homomorphism of degree 0 defined by sending the generators
   [<1>]
 to
   [<Sq(1,2) + Sq(4,1)>]]
sage:

**Comment by sverre320** [comment]
Nice to hear that it worked.  

>I hope that making relative paths was not hard and is not one more thing to maintain (or let go fallow).

Not at all.  In fact, we had made almost all of them relative already, so this was a nice cleanup.

>My goal is to be able to make some module definition files (for Bob Bruner's ext program) for some cyclic modules over the Steenrod algebra.

You almost certainly know this, but there is a method for exporting modules into Bob's Ext-program's format, e.g.

```
sage: A = SteenrodAlgebra(2)
sage: M = FPA_Module([0], A, [[Sq(2)]])
```
This will fail since the module is defined over the entire Steenrod algebra:
```
sage: M.export_module_definition()
ValueError                                Traceback (most recent call last)
    [...]
-> 1121             raise (ValueError, 'this module is not defined over a finite algebra')
```
We must change to a finite sub Hopf-algebra before exporting:
```
sage: A2 = SteenrodAlgebra(2, profile=(3,2,1))
sage: M_fin = M.change_ring(A2)
sage: M_fin.export_module_definition()
[...]
```
Please don't hesitate to report back any problems you may encounter!

**Comment by paultpearson** [comment]
Thanks for the help and advice about exporting modules (i.e., not over A but over a finite sub Hopf algebra A(h)).  

I'm mostly interested in calculating Ext_{A(h)}^{*,*} (M, F_2) for 0 <= h <= 2 for a family of cyclic modules over A.  The Ext_A^{*,*} (M, F_2) computations I want are fortunately already well understood (there are theorems) in a range, so I don't think I'll need to do more computations than I've already done in the past.  (Also, for Ext_A computations, I suppose I could just let h be sufficiently large when defining the module.)
